import type { Teacher } from './types';

export const initialTeachers: Teacher[] = [
  {
    id: '1',
    name: 'מריה גרסיה',
    subjects: ['מתמטיקה', 'פיזיקה'],
    availability: 'שני, רביעי, שישי',
    avatar: { fallback: 'מג' },
    preferences: 'מעדיפה כיתות בוגרות',
  },
  {
    id: '2',
    name: 'דוד סמית',
    subjects: ['אנגלית', 'היסטוריה'],
    availability: 'שלישי, חמישי, שישי',
    avatar: { fallback: 'דס' },
    preferences: 'זמין להחלפות של יום שלם',
  },
  {
    id: '3',
    name: 'חן ווי',
    subjects: ['כימיה', 'ביולוגיה'],
    availability: 'שני, שלישי, רביעי, חמישי',
    avatar: { fallback: 'חו' },
    preferences: 'בעל ניסיון עם חינוך מיוחד',
  },
  {
    id: '4',
    name: ' فاطمة الفاسي',
    subjects: ['אמנות', 'מוזיקה'],
    availability: 'רביעי, שישי',
    avatar: { fallback: 'פא' },
    preferences: '',
  },
  {
    id: '5',
    name: 'מיכאל ג\'ונסון',
    subjects: ['חינוך גופני'],
    availability: 'כל יום',
    avatar: { fallback: 'מג' },
    preferences: 'יכול לאמן גם קבוצות ספורט',
  },
  {
    id: '6',
    name: 'אמילי וויליאמס',
    subjects: ['מתמטיקה', 'מדעי המחשב'],
    availability: 'שלישי, חמישי',
    avatar: { fallback: 'או' },
    preferences: 'מעדיפה בקרים',
  },
  {
    id: '7',
    name: 'דניאל בראון',
    subjects: ['היסטוריה', 'גיאוגרפיה'],
    availability: 'שני, שישי',
    avatar: { fallback: 'דב' },
    preferences: '',
  },
  {
    id: '8',
    name: 'אוליביה ג\'ונס',
    subjects: ['ספרדית', 'צרפתית'],
    availability: 'שני, רביעי, חמישי',
    avatar: { fallback: 'אג' },
    preferences: 'דוברת שפת אם',
  },
];
