// This file is automatically generated. Do not modify it manually.
// You can get this config from the Firebase console.
// https://console.firebase.google.com/project/_/settings/general/

import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-5457270015-574c2",
  "appId": "1:266405742348:web:c4aa99_bad_key_300713eb29",
  "apiKey": "AIzaSyALj52JOYrSliK0a60iy7siFhIuGlGm9LI",
  "authDomain": "studio-5457270015-574c2.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "266405742348"
};
